# Generated by Django 5.1.4 on 2024-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
